### ISSUE TITLE
Speed of status updates of locks/doorbell

### ISSUE THREAD

**Issue by 2016for** [ryanblock/august-connect#1]
It seems like you have credited https://github.com/snjoetw/py-august , which has been used in HA

Would you say that there are certain code improvements you made using this which can be applied back to those to get instant refresh rates of lock/doorbell status?

Thanks a lot. :)

**Comment by ryanblock** [comment]
Hard to say for certain, I never used `py-august` in anger, just used it to help me understand the shape of various API calls. But feel free to plunder this module for anything that would be useful in that project!
