### ISSUE TITLE
Save session to db?

### ISSUE THREAD

**Issue by wootwoot1234** [ryanblock/august-connect#35]
I just came across this library and am very impressed.  I used it today to log into my account and list my locks.  It worked great.  My question is, I plan to use this with multiple august accounts, can you do that with this library?  Where is the access token stored?

**Comment by ryanblock** [comment]
Nice! Per the #38, the session token is not stored anywhere (intentionally); JWT tokens are short-lived. What is the problem you're looking to solve?

**Comment by ryanblock** [comment]
Quick followup: I did just notice that I'm still throwing without the correct env vars – that will go away in the next RC.

**Comment by wootwoot1234** [comment]
I’ll close this issue because it’s being covered in the issue you referenced. I think we should expose the access token and allow uses to use it if they want.
