### ISSUE TITLE
Pings /session with every request?

### ISSUE THREAD

**Issue by wootwoot1234** [ryanblock/august-connect#38]
Is it necessary to call https://api-production.august.com/session with every request?  Is that something that only needs to be called after a period of time on inactivity?  For example, if you check a lock's status and then lock it, do you need to call /session for each of those calls or only once right before you check the lock's status and not after that.  I think it's a good idea to limit the number of requests to august servers if as much as possible.

Maybe it would be a good idea to bring that out as its own method and allow users to call it when they think it's necessary?  

Or maybe there is an error that august returns when /session needs to be pinged and then /session is called?

**Comment by ryanblock** [comment]
It's been a while, but as I recall, yes, you do. This is in part because their API relies on JWTs (which are not intended to be long lived tokens), but also because I designed the client to run statelessly. What is the issue, exactly?

**Comment by wootwoot1234** [comment]
I’m starting to see a too many calls error when I take a series of steps. I think it’s a good idea to reduce the number of calls to make sure the accounts I use with the api aren’t flagged or something. 

After playing with the api over the weekend, I realized that a new access token is returned with every api call and I think we should be using it. It removes the necessity to call the /session endpoint so often. It might be a good idea to return that access token with each call and to supply an access token with each call.

**Comment by ryanblock** [comment]
Ah, I haven't seen that myself, super interesting. Sounds like you're right that it'd be worth passing back and accepting the session token for a series of events. Lmk if you want to take a stab at a PR, if not I might be able to get to it later this week. Docs here will be important tho bc as mentioned, this token should not be persisted.

**Comment by ryanblock** [comment]
Added in https://github.com/ryanblock/august-connect/pull/34/commits/394c8c322824c0c0b2ec9c85dfc1f665806bfcbc, will be released in 3.0!
