### ISSUE TITLE
WiFi Enabled August Doorbell Pro 3rd Gen Ready?

### ISSUE THREAD

**Issue by whreams** [ryanblock/august-connect#39]
Curious if this will work without the August Connect even though I have a WiFi access using other hardware?  Even though I don't have a August Connect, I do have:

-August Lock 3rd Gen Pro.
-August Home AUG-AB02-M02-G02 Dark Gray August Doorbell Cam Pro

**Comment by ryanblock** [comment]
See: https://github.com/ryanblock/august-connect#notes

My guess is that it'll probably work, but I couldn't tell you because I don't have that hardware. Please do let us know!
