### ISSUE TITLE
Add the battery level from the api to the locks or status calls or a new battery call.

### ISSUE THREAD

**Issue by techyowl** [ryanblock/august-connect#40]
I know that certain August APIs used to provide a battery level. If that is something available from one of the endpoints can you expose that metric for the locks? Simple unlock and lock status and control isn't the only helpful information from their apis. Might be useful to reference the py-august repo.

**Comment by ryanblock** [comment]
PRs welcome!

**Comment by techyowl** [comment]
PR is ready for review

**Comment by techyowl** [comment]
Bumping this to make sure my PR doesn't get abandoned.

**Comment by ryanblock** [comment]
Ah sorry! Will give it a peep right now.
