### ISSUE TITLE
[OK]3rd gen lock compatibility

### ISSUE THREAD

**Issue by lifeking4** [ryanblock/august-connect#46]
FYI
My 3rd gen locks can be controlled with this lib, authorization, getting state and lock/unlock works as described.
I tried with...
(1) 3rd gen lock with door sens + doorbell pro
(2) 3rd gen lock with door sens + wifi bridge

In case of doorbell combination, the API response is sometimes delayed for 3-5 sec.
But I guess its a problem of August server because I experienced same issue with Android app.

**Comment by ryanblock** [comment]
That's great news!
