### ISSUE TITLE
Is this repo maintained?

### ISSUE THREAD

**Issue by hufftheweevil** [ryanblock/august-connect#50]
I am going to develop a new August node for Node-RED, and I have been researching this module to use as the underlying API. I see that [techyowl](https://github.com/techyowl/august-connect-api) forked and requested a PR that was never included here, and it appears he gave up and published his own version on npm. I'd like to utilize more endpoints than what is included in either of these modules. So I'm trying to decide if I should start publish my own version, or just fork this and request some PRs to expand it. If I submit some PRs, will you be active in this repo?

**Comment by ryanblock** [comment]
Happy to look at any PRs – the better tested, the higher the likelihood I'll get to it quickly. I think I just lost track of @techyowl's PR, thanks for the reminder.

**Comment by ryanblock** [comment]
Update: looks like that PR [did not work consistently](https://github.com/ryanblock/august-connect/pull/41#issuecomment-1100917449). ¯\_(ツ)_/¯

**Comment by hufftheweevil** [comment]
I see you guys were able to figure it out and merge the PR. After reviewing further, I think I might try my own implementation. I'd like to expand to more endpoints, including subscription of events if possible. But honestly I can't work with all the callbacks here. So I'll just fork and work on that for now. Will get back to you to see if you want to do anything with it after I'm done.
Also, for anyone else interested, I will be building a new Node-RED module based on my fork, once that is complete. Thanks for working on this @ryanblock !

**Comment by ryanblock** [comment]
Sounds fine. I’d been thinking about a refactor to use async / await, if that’s of any consequence. Feel free to PR (or not)!

**Comment by hufftheweevil** [comment]
Just thought I'd mention here that I decided to completely refactor the whole library and publish under a new name: [august-api](https://github.com/hufftheweevil/august-api). Credit added in the acknowledgements to you.

 I also designed a Node-RED that uses it: [node-red-contrib-august](https://github.com/hufftheweevil/node-red-contrib-august)
